{% set name = "ccdproc" %}
{% set version = "2.5.1" %}

package:
  version: {{ version }}
  name: {{ name|lower }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 051b42884cd3188e22dbd2d788c37e0d57bead7c906e479da9a2ecabb44ebdfa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - astropy-base >=5.0.1
    - numpy >=1.24
    - scipy
    - astroscrappy >=1.1.0
    - reproject >=0.7
    - scikit-image

test:
  requires:
    - python {{ python_min }}
  imports:
    - ccdproc
    - ccdproc.utils

about:
  home: http://ccdproc.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Astropy affiliated package for reducing optical/IR CCD data
  description: |
    Ccdproc is an affiliated package for the AstroPy package for basic data
    reductions of CCD images. The ccdproc package provides many of the
    necessary tools for processing of ccd images built on a framework to
    provide error propagation and bad pixel tracking throughout the reduction
    process.
  doc_url: http://ccdproc.readthedocs.io/
  dev_url: https://github.com/astropy/ccdproc

extra:
  recipe-maintainers:
    - mwcraig
    - crawfordsm
    - MSeifert04
    - bsipocz
