{% set name = "ccdproc" %}
{% set version = "2.3.1" %}

package:
  version: {{ version }}
  name: {{ name|lower }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 08e2bf66c67ae773caadeebf2045fb35df531039921510a7b8d6e44fe36f5624

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - setuptools_scm
  run:
    - python >=3.7
    - astropy >=4.0.6
    - numpy >=1.17
    - scipy
    - astroscrappy >=1.0.8
    - reproject >=0.7
    - scikit-image

test:
  imports:
    - ccdproc
    - ccdproc.utils

about:
  home: http://ccdproc.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Astropy affiliated package for reducing optical/IR CCD data
  description: |
    Ccdproc is an affiliated package for the AstroPy package for basic data
    reductions of CCD images. The ccdproc package provides many of the
    necessary tools for processing of ccd images built on a framework to
    provide error propagation and bad pixel tracking throughout the reduction
    process.
  doc_url: http://ccdproc.readthedocs.io/
  dev_url: https://github.com/astropy/ccdproc

extra:
  recipe-maintainers:
    - mwcraig
    - crawfordsm
    - MSeifert04
    - bsipocz
