travis:
  secure:
    BINSTAR_TOKEN: hvOGLjSFAhy2vgk/x71IHbmijlTiyuDmfSMG9749dueOZDUr1YJlsdiTue38ikqn7n4HvvB0EGT+yJqboaDbBEBNHWCs1xBlPWLTZXHYJdbGucDVv33aZLHcJhKCQE3kVmJKGZFDXLMDvI2CMAM3AqFvGzwlnpGT7lZCiwd/zlffSAUCvWXU3pFj+/HBD1rWd2RqhduuBsp7QA26uzwOB+cpnwMmjM9iIfmkKMuoBji6BiPWPHKU/S6blwbYfhPJodI4jz436buoV7g0IeoUwuZ177qwrr2+SuY4cnRvF4wHntnWNCJorL6ra6xZdS92B6mwT+sPk/X+YLRKSDZIAORaH+XyxfhGl197v++teU7xwcBz4Ylzh97r9pH2GdVLx6OmVlzVuYvZb2ZQop7lNDbO+5IPwWwHj20nkujfpd30tNMTr5nAoYJLpDXMWrJXuHFtq5nn02bsXRGhqkzSgzQ8tNyvLCor7fbhrNlIldMxubbfaqkmxnO0v4zNWUfZZJFVgDacC7cRfAU8QKxYLOvTDmP/YMqcQEiacvFHA64tApjWQwl248/blpHUwBIMjzgE5mpiOc1A2FhDgILOqo8JPXnsY270kgbn8Dk1ehLVJBvLkl61mJAZoiTSvcltD87K8/NwmtEwRdZUL3hrTSU1Re8/GbSQuU+ozKvbhhs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
